// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML.Transforms;
using Microsoft.ML;

namespace SAM_Analytical_MachineLearning
{
    public partial class SpaceType
    {
        public const string RetrainFilePath =  @"C:\Users\jakub\GitHub\HoareLea\SAM_MachineLearning\files\resources\Analytical\MachineLearning\Data\SpaceTypes.txt";
        public const char RetrainSeparatorChar = '	';
        public const bool RetrainHasHeader =  true;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader);
        }


        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrain model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(new []{new InputOutputColumnPair(@"adjacentDoor1", @"adjacentDoor1"),new InputOutputColumnPair(@"adjacentDoor2", @"adjacentDoor2"),new InputOutputColumnPair(@"adjacentDoor3", @"adjacentDoor3"),new InputOutputColumnPair(@"adjacentDoor4", @"adjacentDoor4")}, outputKind: OneHotEncodingEstimator.OutputKind.Indicator)      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"volume", @"volume"),new InputOutputColumnPair(@"area", @"area"),new InputOutputColumnPair(@"thinnessRatio", @"thinnessRatio")}))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"name",outputColumnName:@"name"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"adjacentSpace1",outputColumnName:@"adjacentSpace1"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"adjacentSpace2",outputColumnName:@"adjacentSpace2"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"adjacentSpace3",outputColumnName:@"adjacentSpace3"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"adjacentSpace4",outputColumnName:@"adjacentSpace4"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"adjacentDoor1",@"adjacentDoor2",@"adjacentDoor3",@"adjacentDoor4",@"volume",@"area",@"thinnessRatio",@"name",@"adjacentSpace1",@"adjacentSpace2",@"adjacentSpace3",@"adjacentSpace4"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"type",inputColumnName:@"type",addKeyValueAnnotationsAsText:false))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.FastTree(new FastTreeBinaryTrainer.Options(){NumberOfLeaves=4,MinimumExampleCountPerLeaf=20,NumberOfTrees=4,MaximumBinCountPerFeature=254,FeatureFraction=1,LearningRate=0.1,LabelColumnName=@"type",FeatureColumnName=@"Features",DiskTranspose=false}),labelColumnName: @"type"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
 }
