// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace SAM_Analytical_MachineLearning
{
    public partial class SpaceType
    {
        /// <summary>
        /// model input class for SpaceType.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [LoadColumn(0)]
            [ColumnName(@"name")]
            public string Name { get; set; }

            [LoadColumn(1)]
            [ColumnName(@"volume")]
            public float Volume { get; set; }

            [LoadColumn(2)]
            [ColumnName(@"area")]
            public float Area { get; set; }

            [LoadColumn(3)]
            [ColumnName(@"thinnessRatio")]
            public float ThinnessRatio { get; set; }

            [LoadColumn(4)]
            [ColumnName(@"adjacentSpace1")]
            public string AdjacentSpace1 { get; set; }

            [LoadColumn(5)]
            [ColumnName(@"adjacentSpace2")]
            public string AdjacentSpace2 { get; set; }

            [LoadColumn(6)]
            [ColumnName(@"adjacentSpace3")]
            public string AdjacentSpace3 { get; set; }

            [LoadColumn(7)]
            [ColumnName(@"adjacentSpace4")]
            public string AdjacentSpace4 { get; set; }

            [LoadColumn(8)]
            [ColumnName(@"adjacentDoor1")]
            public string AdjacentDoor1 { get; set; }

            [LoadColumn(9)]
            [ColumnName(@"adjacentDoor2")]
            public string AdjacentDoor2 { get; set; }

            [LoadColumn(10)]
            [ColumnName(@"adjacentDoor3")]
            public string AdjacentDoor3 { get; set; }

            [LoadColumn(11)]
            [ColumnName(@"adjacentDoor4")]
            public string AdjacentDoor4 { get; set; }

            [LoadColumn(12)]
            [ColumnName(@"type")]
            public string Type { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for SpaceType.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"name")]
            public float[] Name { get; set; }

            [ColumnName(@"volume")]
            public float Volume { get; set; }

            [ColumnName(@"area")]
            public float Area { get; set; }

            [ColumnName(@"thinnessRatio")]
            public float ThinnessRatio { get; set; }

            [ColumnName(@"adjacentSpace1")]
            public float[] AdjacentSpace1 { get; set; }

            [ColumnName(@"adjacentSpace2")]
            public float[] AdjacentSpace2 { get; set; }

            [ColumnName(@"adjacentSpace3")]
            public float[] AdjacentSpace3 { get; set; }

            [ColumnName(@"adjacentSpace4")]
            public float[] AdjacentSpace4 { get; set; }

            [ColumnName(@"adjacentDoor1")]
            public float[] AdjacentDoor1 { get; set; }

            [ColumnName(@"adjacentDoor2")]
            public float[] AdjacentDoor2 { get; set; }

            [ColumnName(@"adjacentDoor3")]
            public float[] AdjacentDoor3 { get; set; }

            [ColumnName(@"adjacentDoor4")]
            public float[] AdjacentDoor4 { get; set; }

            [ColumnName(@"type")]
            public uint Type { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public string PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("SpaceType.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict scores for all possible labels.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static IOrderedEnumerable<KeyValuePair<string, float>> PredictAllLabels(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            var result = predEngine.Predict(input);
            return GetSortedScoresWithLabels(result);
        }

        /// <summary>
        /// Map the unlabeled result score array to the predicted label names.
        /// </summary>
        /// <param name="result">Prediction to get the labeled scores from.</param>
        /// <returns>Ordered list of label and score.</returns>
        /// <exception cref="Exception"></exception>
        public static IOrderedEnumerable<KeyValuePair<string, float>> GetSortedScoresWithLabels(ModelOutput result)
        {
            var unlabeledScores = result.Score;
            var labelNames = GetLabels(result);

            Dictionary<string, float> labledScores = new Dictionary<string, float>();
            for (int i = 0; i < labelNames.Count(); i++)
            {
                // Map the names to the predicted result score array
                var labelName = labelNames.ElementAt(i);
                labledScores.Add(labelName.ToString(), unlabeledScores[i]);
            }

            return labledScores.OrderByDescending(c => c.Value);
        }

        /// <summary>
        /// Get the ordered label names.
        /// </summary>
        /// <param name="result">Predicted result to get the labels from.</param>
        /// <returns>List of labels.</returns>
        /// <exception cref="Exception"></exception>
        private static IEnumerable<string> GetLabels(ModelOutput result)
        {
            var schema = PredictEngine.Value.OutputSchema;

            var labelColumn = schema.GetColumnOrNull("type");
            if (labelColumn == null)
            {
                throw new Exception("type column not found. Make sure the name searched for matches the name in the schema.");
            }

            // Key values contains an ordered array of the possible labels. This allows us to map the results to the correct label value.
            var keyNames = new VBuffer<ReadOnlyMemory<char>>();
            labelColumn.Value.GetKeyValues(ref keyNames);
            return keyNames.DenseValues().Select(x => x.ToString());
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }
    }
}
